import { ChunkComponent } from "./types";

export const countLines: ChunkComponent[] = [
  {
    id: "card1",
    op: "root",
    type: "element",
    component: "Card",
    props: { expr: '{ "title": dyn("Counter") }' },
    deps: ["scopes.root.count"],
    defaults: [{ set: "scopes.root.count", literal: 0 }],
    children: ["count-text", "count-btn"],
  },
  {
    id: "count-text",
    op: "child",
    type: "element",
    component: "Text",
    props: {
      expr: '{ "children": scopes.root.count, "variant": dyn("large") }',
    },
    deps: ["scopes.root.count"],
  },
  {
    id: "count-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Increment" } },
    callbacks: {
      onClick: [{ set: "scopes.root.count", expr: "scopes.root.count + 1.0" }],
    },
  },
] as const;

export const formLines: ChunkComponent[] = [
  {
    id: "card2",
    op: "root",
    type: "element",
    component: "Card",
    props: { literal: { title: "Form Example" } },
    defaults: [{ set: "scopes.root.count", literal: 0 }],
    children: ["field1"],
  },
  {
    id: "field1",
    op: "child",
    type: "element",
    component: "Field",
    children: ["field1-label", "input1", "field1-desc"],
  },
  {
    id: "field1-label",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Count" } },
  },
  {
    id: "input1",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{ "value": dyn(scopes.root.count), "type": dyn("number") }',
    },
    deps: ["scopes.root.count"],
    callbacks: {
      onChange: [{ set: "scopes.root.count", expr: "evt.valueAsNumber" }],
    },
  },
  {
    id: "field1-desc",
    op: "child",
    type: "element",
    component: "FieldDescription",
    props: { literal: { children: "Enter a number value" } },
  },
] as const;

export const listLines: ChunkComponent[] = [
  {
    id: "list-card",
    op: "root",
    type: "element",
    component: "Card",
    props: { literal: { title: "Dynamic List" } },
    children: ["list-items", "add-item-button"],
    defaults: [
      { set: "scopes.root.items", literal: ["Item 1", "Item 2", "Item 3"] },
    ],
  },
  {
    id: "list-items",
    op: "child",
    type: "list",
    itemScope: "itemScope",
    component: "FlexRow",
    items: { expr: "scopes.root.items" },
    props: { literal: { gap: "2" } },
    children: ["item-badge"],
  },
  {
    id: "item-badge",
    op: "child",
    type: "element",
    component: "Badge",
    props: { expr: '{ "children": scopes.itemScope.item }' },
  },
  {
    id: "add-item-button",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Add Item", variant: "outline" } },
    callbacks: {
      onClick: [
        {
          set: "scopes.root.items",
          expr: 'scopes.root.items + ["Item " + string(size(scopes.root.items) + 1)]',
        },
      ],
    },
  },
] as const;

export const tableLines: ChunkComponent[] = [
  {
    id: "table-card",
    component: "Table",
    op: "root",
    type: "element",
    defaults: [
      { set: "scopes.root.rows", literal: [{ id: 1.0, a: 0.0, b: 0.0 }] },
      { set: "scopes.root.nextId", literal: 2.0 },
      { set: "scopes.root.totalSum", literal: 0.0 },
    ],
    children: ["thead", "tbody", "tfoot"],
  },
  {
    id: "thead",
    component: "TableHeader",
    op: "child",
    type: "element",
    children: ["header-row"],
  },
  {
    id: "header-row",
    component: "TableRow",
    op: "child",
    type: "element",
    children: ["th-a", "th-b", "th-sum", "th-actions"],
  },
  {
    id: "th-a",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "A" } },
  },
  {
    id: "th-b",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "B" } },
  },
  {
    id: "th-sum",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "Sum" } },
  },
  {
    id: "th-actions",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "Actions" } },
  },
  {
    id: "tbody",
    component: "TableBody",
    op: "child",
    type: "element",
    children: ["data-rows"],
  },
  {
    id: "data-rows",
    component: "TableRow",
    op: "child",
    type: "list",
    idKey: "id",
    items: { expr: "scopes.root.rows" },
    itemScope: "row",
    children: ["td-input-a", "td-input-b", "td-sum", "td-delete"],
  },
  {
    id: "td-input-a",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["input-a"],
  },
  {
    id: "input-a",
    component: "NumberInput",
    op: "child",
    type: "element",
    props: { expr: '{"value": scopes.row.item.a}' },
    deps: ["scopes.row.item.a"],
    callbacks: {
      onChange: [
        { set: "scopes.row.item.a", expr: "evt.value" },
        {
          set: "scopes.root.totalSum",
          expr: "reduce(scopes.root.childScopes.row, 0.0, acc, r, acc + double(r.item.a) + double(r.item.b))",
        },
      ],
    },
  },
  {
    id: "td-input-b",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["input-b"],
  },
  {
    id: "input-b",
    component: "NumberInput",
    op: "child",
    type: "element",
    props: { expr: '{"value": scopes.row.item.b}' },
    deps: ["scopes.row.item.b"],
    callbacks: {
      onChange: [
        { set: "scopes.row.item.b", expr: "evt.value" },
        {
          set: "scopes.root.totalSum",
          expr: "reduce(scopes.root.childScopes.row, 0.0, acc, r, acc + double(r.item.a) + double(r.item.b))",
        },
      ],
    },
  },
  {
    id: "td-sum",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["sum-text"],
  },
  {
    id: "sum-text",
    component: "Text",
    op: "child",
    type: "element",
    props: {
      expr: '{"children": double(scopes.row.item.a) + double(scopes.row.item.b)}',
    },
    deps: ["scopes.row.item.a", "scopes.row.item.b"],
  },
  {
    id: "td-delete",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["delete-btn"],
  },
  {
    id: "delete-btn",
    component: "Button",
    op: "child",
    type: "element",
    props: {
      literal: { children: "Delete", variant: "destructive", size: "sm" },
    },
    callbacks: {
      onClick: [
        {
          set: "scopes.root.rows",
          expr: "scopes.root.rows.filter(r, r.id != scopes.row.item.id)",
        },
        {
          set: "scopes.root.totalSum",
          expr: "reduce(scopes.root.childScopes.row, 0.0, acc, r, acc + double(r.item.a) + double(r.item.b))",
        },
      ],
    },
  },
  {
    id: "tfoot",
    component: "TableFooter",
    op: "child",
    type: "element",
    children: ["footer-row"],
  },
  {
    id: "footer-row",
    component: "TableRow",
    op: "child",
    type: "element",
    children: ["td-total-label", "td-add-btn", "td-total-sum", "td-row-count"],
  },
  {
    id: "td-total-label",
    component: "TableCell",
    op: "child",
    type: "element",
    props: { literal: { children: "Total" } },
  },
  {
    id: "td-add-btn",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["add-btn"],
  },
  {
    id: "add-btn",
    component: "Button",
    op: "child",
    type: "element",
    props: {
      literal: { children: "+ Add Row", variant: "outline", size: "sm" },
    },
    callbacks: {
      onClick: [
        {
          set: "scopes.root.rows",
          expr: "scopes.root.rows + [{'id': dyn(scopes.root.nextId), 'a': dyn(0.0), 'b': dyn(0.0)}]",
        },
        { set: "scopes.root.nextId", expr: "scopes.root.nextId + 1.0" },
      ],
    },
  },
  {
    id: "td-total-sum",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["total-sum-text"],
  },
  {
    id: "total-sum-text",
    component: "Text",
    op: "child",
    type: "element",
    props: { expr: '{"children": scopes.root.totalSum}' },
    deps: ["scopes.root.totalSum"],
  },
  {
    id: "td-row-count",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["row-count-text"],
  },
  {
    id: "row-count-text",
    defaults: [
      {
        set: "scopes.root.foo",
        expr: "size(UserRPC_getUsers())",
      },
    ],
    component: "Text",
    op: "child",
    type: "element",
    props: {
      expr: '{"children": string(size(scopes.root.rows)) + " rows " + string(scopes.root.foo) }',
    },
    deps: ["scopes.root.rows"],
  },
] as const;

export const asyncLines: ChunkComponent[] = [
  {
    id: "users-table",
    component: "Table",
    op: "root",
    type: "element",
    defaults: [
      {
        set: "scopes.root.users",
        expr: "UserRPC_getUsers()",
      },
    ],
    children: ["users-thead", "users-tbody"],
  },
  {
    id: "users-thead",
    component: "TableHeader",
    op: "child",
    type: "element",
    children: ["users-header-row"],
  },
  {
    id: "users-header-row",
    component: "TableRow",
    op: "child",
    type: "element",
    children: ["th-name", "th-email"],
  },
  {
    id: "th-name",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "Name" } },
  },
  {
    id: "th-email",
    component: "TableHead",
    op: "child",
    type: "element",
    props: { literal: { children: "Email" } },
  },
  {
    id: "users-tbody",
    component: "TableBody",
    op: "child",
    type: "element",
    children: ["user-rows"],
  },
  {
    id: "user-rows",
    component: "TableRow",
    op: "child",
    type: "list",
    idKey: "id",
    items: { expr: "scopes.root.users" },
    itemScope: "user",
    children: ["td-name", "td-email"],
  },
  {
    id: "td-name",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["name-text"],
  },
  {
    id: "name-text",
    component: "Text",
    op: "child",
    type: "element",
    props: { expr: '{"children": scopes.user.item.fullName}' },
    deps: ["scopes.user.item.fullName"],
  },
  {
    id: "td-email",
    component: "TableCell",
    op: "child",
    type: "element",
    children: ["email-text"],
  },
  {
    id: "email-text",
    component: "Text",
    op: "child",
    type: "element",
    props: { expr: '{"children": scopes.user.item.email}' },
    deps: ["scopes.user.item.email"],
  },
] as const;

export const chartLines: ChunkComponent[] = [
  {
    id: "chart-root",
    op: "root",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    defaults: [
      { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
      { set: "scopes.root.users", expr: "UserRPC_getUsers()" },
      {
        set: "scopes.root.barChartData",
        expr: '[{"status": "TODO", "count": string(size(scopes.root.tasks.filter(t, t.status == "TODO")))}, {"status": "In Progress", "count": string(size(scopes.root.tasks.filter(t, t.status == "IN_PROGRESS")))}, {"status": "Done", "count": string(size(scopes.root.tasks.filter(t, t.status == "DONE")))}]',
      },
      {
        set: "scopes.root.pieChartData",
        expr: 'scopes.root.users.map(u, {"name": u.fullName, "value": dyn(double(size(scopes.root.tasks.filter(t, t.userId == u.id))))})',
      },
    ],
    children: ["bar-card", "pie-card"],
  },
  {
    id: "bar-card",
    op: "child",
    type: "element",
    component: "Card",
    props: { literal: { title: "Tasks by Status" } },
    children: ["status-bar-chart"],
  },
  {
    id: "status-bar-chart",
    op: "child",
    type: "element",
    component: "BarChart",
    props: {
      expr: '{"data": dyn(scopes.root.barChartData), "xKey": dyn("status"), "yKeys": dyn(["count"]), "height": dyn(300)}',
    },
    deps: ["scopes.root.barChartData"],
  },
  {
    id: "pie-card",
    op: "child",
    type: "element",
    component: "Card",
    props: { literal: { title: "Tasks per User" } },
    defaults: [
      {
        set: "scopes.root.pieChartData",
        expr: 'scopes.root.users.map(u, {"name": u.fullName, "value": dyn(double(size(scopes.root.tasks.filter(t, t.userId == u.id))))})',
      },
    ],
    children: ["user-pie-chart"],
  },
  {
    id: "user-pie-chart",
    op: "child",
    type: "element",
    component: "PieChart",
    props: {
      expr: '{"data": dyn(scopes.root.pieChartData), "height": dyn(300), "donut": dyn(true)}',
    },
    deps: ["scopes.root.pieChartData"],
  },
] as const;

export const claudeLines: ChunkComponent[] = [
  {
    id: "root",
    op: "root",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "6" } },
    defaults: [
      { set: "scopes.root.users", expr: "UserRPC_getUsers()" },
      { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
      { set: "scopes.root.activeTab", literal: "tasks" },
      { set: "scopes.root.searchTerm", literal: "" },
      { set: "scopes.root.showAddTask", literal: false },
      { set: "scopes.root.showAddUser", literal: false },
      { set: "scopes.root.showDeleteTask", literal: false },
      { set: "scopes.root.deleteTaskId", literal: "" },
      { set: "scopes.root.showDeleteUser", literal: false },
      { set: "scopes.root.deleteUserId", literal: "" },
      { set: "scopes.root.newTaskTitle", literal: "" },
      { set: "scopes.root.newTaskDesc", literal: "" },
      { set: "scopes.root.newTaskStatus", literal: "TODO" },
      { set: "scopes.root.newTaskUserId", literal: "" },
      { set: "scopes.root.newUserName", literal: "" },
      { set: "scopes.root.newUserEmail", literal: "" },
      { set: "scopes.root.showEditTask", literal: false },
      { set: "scopes.root.editTaskId", literal: "" },
      { set: "scopes.root.editTaskTitle", literal: "" },
      { set: "scopes.root.editTaskDesc", literal: "" },
      { set: "scopes.root.editTaskStatus", literal: "TODO" },
      { set: "scopes.root.editTaskUserId", literal: "" },
      { set: "scopes.root.showEditUser", literal: false },
      { set: "scopes.root.editUserId", literal: "" },
      { set: "scopes.root.editUserName", literal: "" },
      { set: "scopes.root.editUserEmail", literal: "" },
    ],
    children: [
      "heading",
      "stats-row",
      "charts-row",
      "tabs",
      "add-task-modal",
      "edit-task-modal",
      "delete-task-dialog",
      "add-user-modal",
      "edit-user-modal",
      "delete-user-dialog",
    ],
  },
  {
    id: "heading",
    op: "child",
    type: "element",
    component: "Heading",
    props: {
      literal: { level: "1", children: "Project Management Dashboard" },
    },
  },
  {
    id: "stats-row",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "4", wrap: true } },
    children: ["stat-users", "stat-tasks", "stat-progress", "stat-done"],
  },
  {
    id: "stat-users",
    op: "child",
    type: "element",
    component: "Stat",
    props: {
      expr: '{"label": dyn("Total Users"), "value": dyn(size(scopes.root.users))}',
    },
    deps: ["scopes.root.users"],
  },
  {
    id: "stat-tasks",
    op: "child",
    type: "element",
    component: "Stat",
    props: {
      expr: '{"label": dyn("Total Tasks"), "value": dyn(size(scopes.root.tasks))}',
    },
    deps: ["scopes.root.tasks"],
  },
  {
    id: "stat-progress",
    op: "child",
    type: "element",
    component: "Stat",
    props: {
      expr: '{"label": dyn("In Progress"), "value": dyn(size(scopes.root.tasks.filter(t, t.status == "IN_PROGRESS"))), "trend": dyn("up"), "trendValue": dyn(string(size(scopes.root.tasks.filter(t, t.status == "IN_PROGRESS"))) + " active")}',
    },
    deps: ["scopes.root.tasks"],
  },
  {
    id: "stat-done",
    op: "child",
    type: "element",
    component: "Stat",
    props: {
      expr: '{"label": dyn("Completed"), "value": dyn(size(scopes.root.tasks.filter(t, t.status == "DONE"))), "trend": dyn("up"), "trendValue": dyn(string(size(scopes.root.tasks.filter(t, t.status == "DONE"))) + " done")}',
    },
    deps: ["scopes.root.tasks"],
  },
  {
    id: "charts-row",
    op: "child",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    children: ["bar-chart-card", "pie-chart-card"],
  },
  {
    id: "bar-chart-card",
    op: "child",
    type: "element",
    component: "Card",
    props: { literal: { title: "Tasks by Status" } },
    children: ["bar-chart"],
  },
  {
    id: "bar-chart",
    op: "child",
    type: "element",
    component: "BarChart",
    props: {
      expr: '{"data": dyn([{"status": "TODO", "count": string(size(scopes.root.tasks.filter(t, t.status == "TODO")))}, {"status": "In Progress", "count": string(size(scopes.root.tasks.filter(t, t.status == "IN_PROGRESS")))}, {"status": "In Review", "count": string(size(scopes.root.tasks.filter(t, t.status == "IN_REVIEW")))}, {"status": "Done", "count": string(size(scopes.root.tasks.filter(t, t.status == "DONE")))}]), "xKey": dyn("status"), "yKeys": dyn(["count"]), "height": dyn(300), "colors": dyn(["#6366f1", "#f59e0b", "#8b5cf6", "#22c55e"])}',
    },
    deps: ["scopes.root.tasks"],
  },
  {
    id: "pie-chart-card",
    op: "child",
    type: "element",
    component: "Card",
    props: { literal: { title: "Tasks per Team Member" } },
    children: ["pie-chart"],
  },
  {
    id: "pie-chart",
    op: "child",
    type: "element",
    component: "PieChart",
    props: {
      expr: '{"data": dyn(scopes.root.users.map(u, {"name": u.fullName, "value": dyn(double(size(scopes.root.tasks.filter(t, t.userId == u.id))))})), "height": dyn(300), "donut": dyn(true), "showLabels": dyn(true)}',
    },
    deps: ["scopes.root.tasks", "scopes.root.users"],
  },
  {
    id: "tabs",
    op: "child",
    type: "element",
    component: "Tabs",
    props: { expr: '{"value": dyn(scopes.root.activeTab)}' },
    deps: ["scopes.root.activeTab"],
    callbacks: {
      onValueChange: [{ set: "scopes.root.activeTab", expr: "evt.value" }],
    },
    children: ["tab-list", "tab-content-tasks", "tab-content-team"],
  },
  {
    id: "tab-list",
    op: "child",
    type: "element",
    component: "TabList",
    children: ["tab-trigger-tasks", "tab-trigger-team"],
  },
  {
    id: "tab-trigger-tasks",
    op: "child",
    type: "element",
    component: "TabTrigger",
    props: { literal: { value: "tasks", children: "Tasks Board" } },
  },
  {
    id: "tab-trigger-team",
    op: "child",
    type: "element",
    component: "TabTrigger",
    props: { literal: { value: "team", children: "Team Management" } },
  },
  {
    id: "tab-content-tasks",
    op: "child",
    type: "element",
    component: "TabContent",
    props: { literal: { value: "tasks" } },
    children: ["tasks-toolbar", "tasks-table"],
  },
  {
    id: "tasks-toolbar",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "4", justify: "between", align: "center" } },
    children: ["search-input", "add-task-btn"],
  },
  {
    id: "search-input",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.searchTerm), "placeholder": dyn("Search tasks by title..."), "type": dyn("search")}',
    },
    deps: ["scopes.root.searchTerm"],
    callbacks: {
      onChange: [{ set: "scopes.root.searchTerm", expr: "evt.value" }],
    },
  },
  {
    id: "add-task-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "+ Add Task" } },
    callbacks: { onClick: [{ set: "scopes.root.showAddTask", literal: true }] },
  },
  {
    id: "tasks-table",
    op: "child",
    type: "element",
    component: "Table",
    children: ["tasks-thead", "tasks-tbody"],
  },
  {
    id: "tasks-thead",
    op: "child",
    type: "element",
    component: "TableHeader",
    children: ["tasks-header-row"],
  },
  {
    id: "tasks-header-row",
    op: "child",
    type: "element",
    component: "TableRow",
    children: ["th-title", "th-desc", "th-status", "th-user", "th-actions"],
  },
  {
    id: "th-title",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Title" } },
  },
  {
    id: "th-desc",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Description" } },
  },
  {
    id: "th-status",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Status" } },
  },
  {
    id: "th-user",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Assigned To" } },
  },
  {
    id: "th-actions",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Actions" } },
  },
  {
    id: "tasks-tbody",
    op: "child",
    type: "element",
    component: "TableBody",
    children: ["task-rows"],
  },
  {
    id: "task-rows",
    op: "child",
    type: "list",
    component: "TableRow",
    itemScope: "taskRow",
    idKey: "id",
    items: {
      expr: 'scopes.root.tasks.filter(t, scopes.root.searchTerm == "" || t.title.lowerAscii().contains(scopes.root.searchTerm.lowerAscii()))',
    },
    children: ["td-title", "td-desc", "td-status", "td-user", "td-actions"],
  },
  {
    id: "td-title",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["title-text"],
  },
  {
    id: "title-text",
    op: "child",
    type: "element",
    component: "Text",
    props: { expr: '{"children": dyn(scopes.taskRow.item.title)}' },
    deps: ["scopes.taskRow.item.title"],
  },
  {
    id: "td-desc",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["desc-text"],
  },
  {
    id: "desc-text",
    op: "child",
    type: "element",
    component: "Text",
    props: {
      expr: '{"children": dyn(scopes.taskRow.item.description), "variant": dyn("muted")}',
    },
    deps: ["scopes.taskRow.item.description"],
  },
  {
    id: "td-status",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["status-badge"],
  },
  {
    id: "status-badge",
    op: "child",
    type: "element",
    component: "Badge",
    props: {
      expr: '{"children": dyn(scopes.taskRow.item.status == "IN_PROGRESS" ? "In Progress" : (scopes.taskRow.item.status == "IN_REVIEW" ? "In Review" : (scopes.taskRow.item.status == "DONE" ? "Done" : "To Do"))), "variant": dyn(scopes.taskRow.item.status == "DONE" ? "default" : (scopes.taskRow.item.status == "IN_PROGRESS" ? "secondary" : (scopes.taskRow.item.status == "IN_REVIEW" ? "outline" : "destructive")))}',
    },
    deps: ["scopes.taskRow.item.status"],
  },
  {
    id: "td-user",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["user-name-text"],
  },
  {
    id: "user-name-text",
    op: "child",
    type: "element",
    component: "Text",
    props: {
      expr: '{"children": dyn(cel.bind(matches, scopes.root.users.filter(u, u.id == scopes.taskRow.item.userId), size(matches) > 0 ? matches[0].fullName : "Unassigned"))}',
    },
    deps: ["scopes.taskRow.item.userId", "scopes.root.users"],
  },
  {
    id: "td-actions",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["task-dropdown"],
  },
  {
    id: "task-dropdown",
    op: "child",
    type: "element",
    component: "DropdownMenu",
    children: ["task-edit-item", "task-delete-item"],
  },
  {
    id: "task-edit-item",
    op: "child",
    type: "element",
    component: "DropdownMenuItem",
    props: { literal: { children: "Edit" } },
    callbacks: {
      onClick: [
        { set: "scopes.root.editTaskId", expr: "scopes.taskRow.item.id" },
        { set: "scopes.root.editTaskTitle", expr: "scopes.taskRow.item.title" },
        {
          set: "scopes.root.editTaskDesc",
          expr: "scopes.taskRow.item.description",
        },
        {
          set: "scopes.root.editTaskStatus",
          expr: 'has(scopes.taskRow.item.status) ? scopes.taskRow.item.status : "TODO"',
        },
        {
          set: "scopes.root.editTaskUserId",
          expr: "scopes.taskRow.item.userId",
        },
        { set: "scopes.root.showEditTask", literal: true },
      ],
    },
  },
  {
    id: "task-delete-item",
    op: "child",
    type: "element",
    component: "DropdownMenuItem",
    props: { literal: { children: "Delete", variant: "destructive" } },
    callbacks: {
      onClick: [
        { set: "scopes.root.deleteTaskId", expr: "scopes.taskRow.item.id" },
        { set: "scopes.root.showDeleteTask", literal: true },
      ],
    },
  },
  {
    id: "tab-content-team",
    op: "child",
    type: "element",
    component: "TabContent",
    props: { literal: { value: "team" } },
    children: ["team-toolbar", "users-table"],
  },
  {
    id: "team-toolbar",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "4", justify: "end", align: "center" } },
    children: ["add-user-btn"],
  },
  {
    id: "add-user-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "+ Add User" } },
    callbacks: { onClick: [{ set: "scopes.root.showAddUser", literal: true }] },
  },
  {
    id: "users-table",
    op: "child",
    type: "element",
    component: "Table",
    children: ["users-thead", "users-tbody"],
  },
  {
    id: "users-thead",
    op: "child",
    type: "element",
    component: "TableHeader",
    children: ["users-header-row"],
  },
  {
    id: "users-header-row",
    op: "child",
    type: "element",
    component: "TableRow",
    children: ["uth-name", "uth-email", "uth-tasks", "uth-actions"],
  },
  {
    id: "uth-name",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Full Name" } },
  },
  {
    id: "uth-email",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Email" } },
  },
  {
    id: "uth-tasks",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Task Count" } },
  },
  {
    id: "uth-actions",
    op: "child",
    type: "element",
    component: "TableHead",
    props: { literal: { children: "Actions" } },
  },
  {
    id: "users-tbody",
    op: "child",
    type: "element",
    component: "TableBody",
    children: ["user-rows"],
  },
  {
    id: "user-rows",
    op: "child",
    type: "list",
    component: "TableRow",
    itemScope: "userRow",
    idKey: "id",
    items: { expr: "scopes.root.users" },
    children: ["utd-name", "utd-email", "utd-task-count", "utd-actions"],
  },
  {
    id: "utd-name",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["uname-text"],
  },
  {
    id: "uname-text",
    op: "child",
    type: "element",
    component: "Text",
    props: { expr: '{"children": dyn(scopes.userRow.item.fullName)}' },
    deps: ["scopes.userRow.item.fullName"],
  },
  {
    id: "utd-email",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["uemail-text"],
  },
  {
    id: "uemail-text",
    op: "child",
    type: "element",
    component: "Text",
    props: {
      expr: '{"children": dyn(scopes.userRow.item.email), "variant": dyn("muted")}',
    },
    deps: ["scopes.userRow.item.email"],
  },
  {
    id: "utd-task-count",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["task-count-badge"],
  },
  {
    id: "task-count-badge",
    op: "child",
    type: "element",
    component: "Badge",
    props: {
      expr: '{"children": dyn(size(scopes.root.tasks.filter(t, t.userId == scopes.userRow.item.id))), "variant": dyn("secondary")}',
    },
    deps: ["scopes.root.tasks", "scopes.userRow.item.id"],
  },
  {
    id: "utd-actions",
    op: "child",
    type: "element",
    component: "TableCell",
    children: ["user-dropdown"],
  },
  {
    id: "user-dropdown",
    op: "child",
    type: "element",
    component: "DropdownMenu",
    children: ["user-edit-item", "user-delete-item"],
  },
  {
    id: "user-edit-item",
    op: "child",
    type: "element",
    component: "DropdownMenuItem",
    props: { literal: { children: "Edit" } },
    callbacks: {
      onClick: [
        { set: "scopes.root.editUserId", expr: "scopes.userRow.item.id" },
        {
          set: "scopes.root.editUserName",
          expr: "scopes.userRow.item.fullName",
        },
        { set: "scopes.root.editUserEmail", expr: "scopes.userRow.item.email" },
        { set: "scopes.root.showEditUser", literal: true },
      ],
    },
  },
  {
    id: "user-delete-item",
    op: "child",
    type: "element",
    component: "DropdownMenuItem",
    props: { literal: { children: "Delete", variant: "destructive" } },
    callbacks: {
      onClick: [
        { set: "scopes.root.deleteUserId", expr: "scopes.userRow.item.id" },
        { set: "scopes.root.showDeleteUser", literal: true },
      ],
    },
  },
  {
    id: "add-task-modal",
    op: "child",
    type: "element",
    component: "Modal",
    props: {
      expr: '{"open": dyn(scopes.root.showAddTask), "title": dyn("Add New Task"), "description": dyn("Fill in the details to create a new task.")}',
    },
    deps: ["scopes.root.showAddTask"],
    callbacks: {
      onOpenChange: [{ set: "scopes.root.showAddTask", expr: "evt.open" }],
    },
    children: ["add-task-form"],
  },
  {
    id: "add-task-form",
    op: "child",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    children: [
      "field-new-task-title",
      "field-new-task-desc",
      "field-new-task-status",
      "field-new-task-user",
      "submit-task-row",
    ],
  },
  {
    id: "field-new-task-title",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-task-title", "input-new-task-title"],
  },
  {
    id: "lbl-new-task-title",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Title" } },
  },
  {
    id: "input-new-task-title",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.newTaskTitle), "placeholder": dyn("Enter task title")}',
    },
    deps: ["scopes.root.newTaskTitle"],
    callbacks: {
      onChange: [{ set: "scopes.root.newTaskTitle", expr: "evt.value" }],
    },
  },
  {
    id: "field-new-task-desc",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-task-desc", "input-new-task-desc"],
  },
  {
    id: "lbl-new-task-desc",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Description" } },
  },
  {
    id: "input-new-task-desc",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.newTaskDesc), "placeholder": dyn("Enter task description")}',
    },
    deps: ["scopes.root.newTaskDesc"],
    callbacks: {
      onChange: [{ set: "scopes.root.newTaskDesc", expr: "evt.value" }],
    },
  },
  {
    id: "field-new-task-status",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-task-status", "select-new-task-status"],
  },
  {
    id: "lbl-new-task-status",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Status" } },
  },
  {
    id: "select-new-task-status",
    op: "child",
    type: "element",
    component: "Select",
    props: {
      expr: '{"value": dyn(scopes.root.newTaskStatus), "placeholder": dyn("Select status"), "options": dyn([{"label": "To Do", "value": "TODO"}, {"label": "In Progress", "value": "IN_PROGRESS"}, {"label": "In Review", "value": "IN_REVIEW"}, {"label": "Done", "value": "DONE"}])}',
    },
    deps: ["scopes.root.newTaskStatus"],
    callbacks: {
      onChange: [{ set: "scopes.root.newTaskStatus", expr: "evt.value" }],
    },
  },
  {
    id: "field-new-task-user",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-task-user", "select-new-task-user"],
  },
  {
    id: "lbl-new-task-user",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Assign To" } },
  },
  {
    id: "select-new-task-user",
    op: "child",
    type: "element",
    component: "Select",
    props: {
      expr: '{"value": dyn(scopes.root.newTaskUserId), "placeholder": dyn("Select a user"), "options": dyn(scopes.root.users.map(u, {"label": u.fullName, "value": u.id}))}',
    },
    deps: ["scopes.root.newTaskUserId", "scopes.root.users"],
    callbacks: {
      onChange: [{ set: "scopes.root.newTaskUserId", expr: "evt.value" }],
    },
  },
  {
    id: "submit-task-row",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "2", justify: "end" } },
    children: ["cancel-add-task-btn", "submit-add-task-btn"],
  },
  {
    id: "cancel-add-task-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Cancel", variant: "outline" } },
    callbacks: {
      onClick: [{ set: "scopes.root.showAddTask", literal: false }],
    },
  },
  {
    id: "submit-add-task-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Create Task" } },
    callbacks: {
      onClick: [
        {
          set: "scopes.root._createTaskResult",
          expr: 'TaskRPC_createTask({"body": {"title": scopes.root.newTaskTitle, "description": scopes.root.newTaskDesc, "status": scopes.root.newTaskStatus, "userId": scopes.root.newTaskUserId}})',
        },
        { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
        { set: "scopes.root.showAddTask", literal: false },
        { set: "scopes.root.newTaskTitle", literal: "" },
        { set: "scopes.root.newTaskDesc", literal: "" },
        { set: "scopes.root.newTaskStatus", literal: "TODO" },
        { set: "scopes.root.newTaskUserId", literal: "" },
      ],
    },
  },
  {
    id: "edit-task-modal",
    op: "child",
    type: "element",
    component: "Modal",
    props: {
      expr: '{"open": dyn(scopes.root.showEditTask), "title": dyn("Edit Task"), "description": dyn("Update the task details.")}',
    },
    deps: ["scopes.root.showEditTask"],
    callbacks: {
      onOpenChange: [{ set: "scopes.root.showEditTask", expr: "evt.open" }],
    },
    children: ["edit-task-form"],
  },
  {
    id: "edit-task-form",
    op: "child",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    children: [
      "field-edit-task-title",
      "field-edit-task-desc",
      "field-edit-task-status",
      "field-edit-task-user",
      "submit-edit-task-row",
    ],
  },
  {
    id: "field-edit-task-title",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-task-title", "input-edit-task-title"],
  },
  {
    id: "lbl-edit-task-title",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Title" } },
  },
  {
    id: "input-edit-task-title",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.editTaskTitle), "placeholder": dyn("Enter task title")}',
    },
    deps: ["scopes.root.editTaskTitle"],
    callbacks: {
      onChange: [{ set: "scopes.root.editTaskTitle", expr: "evt.value" }],
    },
  },
  {
    id: "field-edit-task-desc",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-task-desc", "input-edit-task-desc"],
  },
  {
    id: "lbl-edit-task-desc",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Description" } },
  },
  {
    id: "input-edit-task-desc",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.editTaskDesc), "placeholder": dyn("Enter task description")}',
    },
    deps: ["scopes.root.editTaskDesc"],
    callbacks: {
      onChange: [{ set: "scopes.root.editTaskDesc", expr: "evt.value" }],
    },
  },
  {
    id: "field-edit-task-status",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-task-status", "select-edit-task-status"],
  },
  {
    id: "lbl-edit-task-status",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Status" } },
  },
  {
    id: "select-edit-task-status",
    op: "child",
    type: "element",
    component: "Select",
    props: {
      expr: '{"value": dyn(scopes.root.editTaskStatus), "placeholder": dyn("Select status"), "options": dyn([{"label": "To Do", "value": "TODO"}, {"label": "In Progress", "value": "IN_PROGRESS"}, {"label": "In Review", "value": "IN_REVIEW"}, {"label": "Done", "value": "DONE"}])}',
    },
    deps: ["scopes.root.editTaskStatus"],
    callbacks: {
      onChange: [{ set: "scopes.root.editTaskStatus", expr: "evt.value" }],
    },
  },
  {
    id: "field-edit-task-user",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-task-user", "select-edit-task-user"],
  },
  {
    id: "lbl-edit-task-user",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Assign To" } },
  },
  {
    id: "select-edit-task-user",
    op: "child",
    type: "element",
    component: "Select",
    props: {
      expr: '{"value": dyn(scopes.root.editTaskUserId), "placeholder": dyn("Select a user"), "options": dyn(scopes.root.users.map(u, {"label": u.fullName, "value": u.id}))}',
    },
    deps: ["scopes.root.editTaskUserId", "scopes.root.users"],
    callbacks: {
      onChange: [{ set: "scopes.root.editTaskUserId", expr: "evt.value" }],
    },
  },
  {
    id: "submit-edit-task-row",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "2", justify: "end" } },
    children: ["cancel-edit-task-btn", "submit-edit-task-btn"],
  },
  {
    id: "cancel-edit-task-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Cancel", variant: "outline" } },
    callbacks: {
      onClick: [{ set: "scopes.root.showEditTask", literal: false }],
    },
  },
  {
    id: "submit-edit-task-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Save Changes" } },
    callbacks: {
      onClick: [
        {
          set: "scopes.root._updateTaskResult",
          expr: 'TaskRPC_updateTask({"body": {"title": scopes.root.editTaskTitle, "description": scopes.root.editTaskDesc, "status": scopes.root.editTaskStatus, "userId": scopes.root.editTaskUserId}, "params": {"id": scopes.root.editTaskId}})',
        },
        { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
        { set: "scopes.root.showEditTask", literal: false },
      ],
    },
  },
  {
    id: "delete-task-dialog",
    op: "child",
    type: "element",
    component: "ConfirmDialog",
    props: {
      expr: '{"open": dyn(scopes.root.showDeleteTask), "title": dyn("Delete Task"), "description": dyn("Are you sure you want to delete this task? This action cannot be undone."), "confirmLabel": dyn("Delete"), "cancelLabel": dyn("Cancel"), "variant": dyn("destructive")}',
    },
    deps: ["scopes.root.showDeleteTask"],
    callbacks: {
      onConfirm: [
        {
          set: "scopes.root._deleteTaskResult",
          expr: 'TaskRPC_deleteTask({"params": {"id": scopes.root.deleteTaskId}})',
        },
        { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
        { set: "scopes.root.showDeleteTask", literal: false },
        { set: "scopes.root.deleteTaskId", literal: "" },
      ],
      onCancel: [
        { set: "scopes.root.showDeleteTask", literal: false },
        { set: "scopes.root.deleteTaskId", literal: "" },
      ],
    },
  },
  {
    id: "add-user-modal",
    op: "child",
    type: "element",
    component: "Modal",
    props: {
      expr: '{"open": dyn(scopes.root.showAddUser), "title": dyn("Add New User"), "description": dyn("Enter the user details.")}',
    },
    deps: ["scopes.root.showAddUser"],
    callbacks: {
      onOpenChange: [{ set: "scopes.root.showAddUser", expr: "evt.open" }],
    },
    children: ["add-user-form"],
  },
  {
    id: "add-user-form",
    op: "child",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    children: [
      "field-new-user-name",
      "field-new-user-email",
      "submit-user-row",
    ],
  },
  {
    id: "field-new-user-name",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-user-name", "input-new-user-name"],
  },
  {
    id: "lbl-new-user-name",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Full Name" } },
  },
  {
    id: "input-new-user-name",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.newUserName), "placeholder": dyn("Enter full name")}',
    },
    deps: ["scopes.root.newUserName"],
    callbacks: {
      onChange: [{ set: "scopes.root.newUserName", expr: "evt.value" }],
    },
  },
  {
    id: "field-new-user-email",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-new-user-email", "input-new-user-email"],
  },
  {
    id: "lbl-new-user-email",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Email" } },
  },
  {
    id: "input-new-user-email",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.newUserEmail), "placeholder": dyn("Enter email address"), "type": dyn("email")}',
    },
    deps: ["scopes.root.newUserEmail"],
    callbacks: {
      onChange: [{ set: "scopes.root.newUserEmail", expr: "evt.value" }],
    },
  },
  {
    id: "submit-user-row",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "2", justify: "end" } },
    children: ["cancel-add-user-btn", "submit-add-user-btn"],
  },
  {
    id: "cancel-add-user-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Cancel", variant: "outline" } },
    callbacks: {
      onClick: [{ set: "scopes.root.showAddUser", literal: false }],
    },
  },
  {
    id: "submit-add-user-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Create User" } },
    callbacks: {
      onClick: [
        {
          set: "scopes.root._createUserResult",
          expr: 'UserRPC_createUser({"body": {"fullName": scopes.root.newUserName, "email": scopes.root.newUserEmail}})',
        },
        { set: "scopes.root.users", expr: "UserRPC_getUsers()" },
        { set: "scopes.root.showAddUser", literal: false },
        { set: "scopes.root.newUserName", literal: "" },
        { set: "scopes.root.newUserEmail", literal: "" },
      ],
    },
  },
  {
    id: "edit-user-modal",
    op: "child",
    type: "element",
    component: "Modal",
    props: {
      expr: '{"open": dyn(scopes.root.showEditUser), "title": dyn("Edit User"), "description": dyn("Update the user details.")}',
    },
    deps: ["scopes.root.showEditUser"],
    callbacks: {
      onOpenChange: [{ set: "scopes.root.showEditUser", expr: "evt.open" }],
    },
    children: ["edit-user-form"],
  },
  {
    id: "edit-user-form",
    op: "child",
    type: "element",
    component: "FlexCol",
    props: { literal: { gap: "4" } },
    children: [
      "field-edit-user-name",
      "field-edit-user-email",
      "submit-edit-user-row",
    ],
  },
  {
    id: "field-edit-user-name",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-user-name", "input-edit-user-name"],
  },
  {
    id: "lbl-edit-user-name",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Full Name" } },
  },
  {
    id: "input-edit-user-name",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.editUserName), "placeholder": dyn("Enter full name")}',
    },
    deps: ["scopes.root.editUserName"],
    callbacks: {
      onChange: [{ set: "scopes.root.editUserName", expr: "evt.value" }],
    },
  },
  {
    id: "field-edit-user-email",
    op: "child",
    type: "element",
    component: "Field",
    children: ["lbl-edit-user-email", "input-edit-user-email"],
  },
  {
    id: "lbl-edit-user-email",
    op: "child",
    type: "element",
    component: "FieldLabel",
    props: { literal: { children: "Email" } },
  },
  {
    id: "input-edit-user-email",
    op: "child",
    type: "element",
    component: "Input",
    props: {
      expr: '{"value": dyn(scopes.root.editUserEmail), "placeholder": dyn("Enter email address"), "type": dyn("email")}',
    },
    deps: ["scopes.root.editUserEmail"],
    callbacks: {
      onChange: [{ set: "scopes.root.editUserEmail", expr: "evt.value" }],
    },
  },
  {
    id: "submit-edit-user-row",
    op: "child",
    type: "element",
    component: "FlexRow",
    props: { literal: { gap: "2", justify: "end" } },
    children: ["cancel-edit-user-btn", "submit-edit-user-btn"],
  },
  {
    id: "cancel-edit-user-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Cancel", variant: "outline" } },
    callbacks: {
      onClick: [{ set: "scopes.root.showEditUser", literal: false }],
    },
  },
  {
    id: "submit-edit-user-btn",
    op: "child",
    type: "element",
    component: "Button",
    props: { literal: { children: "Save Changes" } },
    callbacks: {
      onClick: [
        {
          set: "scopes.root._updateUserResult",
          expr: 'UserRPC_updateUser({"body": {"fullName": scopes.root.editUserName, "email": scopes.root.editUserEmail}, "params": {"id": scopes.root.editUserId}})',
        },
        { set: "scopes.root.users", expr: "UserRPC_getUsers()" },
        { set: "scopes.root.showEditUser", literal: false },
      ],
    },
  },
  {
    id: "delete-user-dialog",
    op: "child",
    type: "element",
    component: "ConfirmDialog",
    props: {
      expr: '{"open": dyn(scopes.root.showDeleteUser), "title": dyn("Delete User"), "description": dyn("Are you sure you want to delete this user? All tasks assigned to this user will also be removed. This action cannot be undone."), "confirmLabel": dyn("Delete User"), "cancelLabel": dyn("Cancel"), "variant": dyn("destructive")}',
    },
    deps: ["scopes.root.showDeleteUser"],
    callbacks: {
      onConfirm: [
        {
          set: "scopes.root._deleteUserResult",
          expr: 'UserRPC_deleteUser({"params": {"id": scopes.root.deleteUserId}})',
        },
        { set: "scopes.root.users", expr: "UserRPC_getUsers()" },
        { set: "scopes.root.tasks", expr: "TaskRPC_getTasks()" },
        { set: "scopes.root.showDeleteUser", literal: false },
        { set: "scopes.root.deleteUserId", literal: "" },
      ],
      onCancel: [
        { set: "scopes.root.showDeleteUser", literal: false },
        { set: "scopes.root.deleteUserId", literal: "" },
      ],
    },
  },
];
